"""
SFT Training Script for Qwen2.5-3B-Instruct as a BM25 Tool-Use Agent.

Optimized for a 48GB GPU (e.g. A40, A6000, L40S).
Full-parameter fine-tuning with gradient checkpointing.
"""

import os
import gc
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq,
)

# Prevent CUDA memory fragmentation
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

# ---------------------------------------------------------------------------
# 1. CONFIGURATION
# ---------------------------------------------------------------------------

MODEL_ID = "Qwen/Qwen2.5-3B-Instruct"      # 3.09B parameters
DATASET_PATH = "train_data_3b.jsonl"          # Generated by prepare_data_3b.py
OUTPUT_DIR = "./qwen-3b-bm25-sft"
MAX_SEQ_LEN = 1024                            # 3B can handle longer context

# ---------------------------------------------------------------------------
# 2. TOKENIZER SETUP
# ---------------------------------------------------------------------------

print(f"Loading tokenizer from {MODEL_ID}...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# ---------------------------------------------------------------------------
# 3. LOAD FULL BASE MODEL
# ---------------------------------------------------------------------------

print(f"Loading base model {MODEL_ID} in BFloat16...")
dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=dtype,
    device_map="auto",
    trust_remote_code=True,
)

# Gradient checkpointing saves activation memory during backward pass
model.gradient_checkpointing_enable()

# Ensure 100% of parameters receive full gradient updates
for param in model.parameters():
    param.requires_grad = True

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
total_params = sum(p.numel() for p in model.parameters())
print(f"Total Parameters: {total_params:,}")
print(f"Trainable Parameters (100%): {trainable_params:,}")

# ---------------------------------------------------------------------------
# 4. PREPARE DATASET
# ---------------------------------------------------------------------------

print(f"Loading dataset from {DATASET_PATH}...")
raw_dataset = load_dataset("json", data_files=DATASET_PATH, split="train")
print(f"Dataset size: {len(raw_dataset)} examples")

def preprocess_function(example):
    """Apply chat template and tokenize."""
    messages = example["messages"]
    text = tokenizer.apply_chat_template(messages, tokenize=False)
    tokenized = tokenizer(
        text,
        truncation=True,
        max_length=MAX_SEQ_LEN,
        padding=False,
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

tokenized_dataset = raw_dataset.map(
    preprocess_function,
    remove_columns=raw_dataset.column_names,
    desc="Tokenizing dataset",
)

# Print dataset statistics
lengths = [len(x["input_ids"]) for x in tokenized_dataset]
print(f"Token length stats: min={min(lengths)}, max={max(lengths)}, "
      f"mean={sum(lengths)/len(lengths):.0f}")

# ---------------------------------------------------------------------------
# 5. TRAINING ARGUMENTS  (48GB GPU — can be generous)
# ---------------------------------------------------------------------------

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size=4,          # 48GB VRAM allows larger batches
    gradient_accumulation_steps=4,          # Effective batch size = 16
    learning_rate=2e-5,                     # Slightly lower LR for 3B model
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,                      # 5% warmup
    logging_steps=5,
    num_train_epochs=3,
    save_strategy="epoch",
    save_total_limit=2,
    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported(),
    optim="adamw_torch",
    gradient_checkpointing=True,
    report_to="none",
    dataloader_num_workers=4,
    weight_decay=0.01,
)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator,
)

# ---------------------------------------------------------------------------
# 6. RUN FULL TRAINING & SAVE WEIGHTS
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print(f"\n{'='*70}")
    print(f"Starting full-parameter SFT on {MODEL_ID}")
    print(f"  Dataset: {len(tokenized_dataset)} examples")
    print(f"  Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
    print(f"  Epochs: {training_args.num_train_epochs}")
    print(f"  Learning rate: {training_args.learning_rate}")
    print(f"  Max sequence length: {MAX_SEQ_LEN}")
    print(f"{'='*70}\n")

    trainer.train()

    print(f"\nSaving full model weights and tokenizer to {OUTPUT_DIR}...")
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print("SFT training finished successfully!")
